# Do NOT update manually; changes here will be overwritten by Copier
_commit: v2.1.2
_src_path: https://github.com/coopiteasy/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Coop IT Easy SC
org_slug: coopiteasy
rebel_module_groups: []
repo_description: Resource management by Coop IT Easy
repo_name: CIE Resource
repo_slug: cie-resource
repo_website: https://github.com/coopiteasy/cie-resource
travis_apt_packages: []
travis_apt_sources: []

